### ISSUE TITLE
400 bug

### ISSUE THREAD

**Issue by jayaraj-dckap** [klevultd/frontend-sdk#103]
While I am trying to integrate the recommended products I am getting 400 errors.

![image](https://user-images.githubusercontent.com/92306881/182593837-b98e2f8d-8e11-4c26-a780-4eda21800a8e.png)
![image](https://user-images.githubusercontent.com/92306881/182593884-009db567-62c0-40ca-9381-a673a5532097.png)
This is the code I have integrated. Am I missing something?

But am getting a response correctly then why am getting 400 error 

![image](https://user-images.githubusercontent.com/92306881/182593932-8335f24c-2b93-4dbb-9f2a-fb0a702d3a7b.png)

**Comment by rallu** [comment]
Hello. Can you paste request going to Klevu backend from network tab? Filter with `v2/search` and you should see only requests to Klevu API. Especially payload tab would be nice to see from that request.

**Comment by jayaraj-dckap** [comment]
[
	{
		"event": "view_recs_list",
		"event_apikey": "klevu-163280462753814066",
		"event_list_id": "k-1412e846-9760-4968-956a-9115bd2e543a",
		"event_list_logic": "TRENDING",
		"event_list_name": "Trending recommendations using KMC builder personalised",
		"items": [
			{
				"currency": "CAD",
				"index": 1,
				"item_category": "Safety Switches",
				"item_group_id": "175006",
				"item_id": "175006",
				"item_name": "Safety switch, Telemecanique Safety switches XCS, metal XCSLF, 4 NC+ 2 NO, slow break, 3 entries tapped M20, 24 V",
				"item_variant_id": "175006",
				"price": "430.63"
			},
			{
				"currency": "CAD",
				"index": 2,
				"item_category": "Push Buttons",
				"item_group_id": "171678",
				"item_id": "171678",
				"item_name": "30mm push button, Type K, illuminated maintained push pull mushroom, 120VAC/VDC red LED, red mushroom, NEMA 4, 13",
				"item_variant_id": "171678",
				"price": "307.01"
			},
			{
				"currency": "CAD",
				"index": 3,
				"item_category": "Heating Cords",
				"item_group_id": "767417",
				"item_id": "767417",
				"item_name": "Thermo-Shrink® Underground Splice Kit, 1/0-250 MCM",
				"item_variant_id": "767417",
				"price": "59.58"
			},
			{
				"currency": "CAD",
				"index": 4,
				"item_group_id": "1",
				"item_id": "1",
				"item_name": "Braided Bonding Strap, Two-Hole, Non-Ins",
				"item_variant_id": "1",
				"price": "166.90"
			},
			{
				"currency": "CAD",
				"index": 5,
				"item_category": "End Caps",
				"item_group_id": "132317",
				"item_id": "132317",
				"item_name": "FS EDPM TWIN TOWER CAP 1/0 2.625 IN",
				"item_variant_id": "132317",
				"price": "18.19"
			},
			{
				"currency": "CAD",
				"index": 6,
				"item_category": "Molded Case Circuit Breakers",
				"item_group_id": "102794",
				"item_id": "102794",
				"item_name": "MOLDED CASE CIRCUIT BREAKER 600V 1200A",
				"item_variant_id": "102794",
				"price": "23539.57"
			},
			{
				"currency": "CAD",
				"index": 7,
				"item_group_id": "664354",
				"item_id": "664354",
				"item_name": "Eaton B-Line series strut fiberglass channel and fittings, 2\" channel height, 240\" channel length, 1.62\" channel width, Vinyl polyester resin",
				"item_variant_id": "664354",
				"price": "176.72"
			},
			{
				"currency": "CAD",
				"index": 8,
				"item_category": "Splice & Taps",
				"item_group_id": "224647",
				"item_id": "224647",
				"item_name": "Insulated AL service entrance compression sleeve for combinations of insulated CU, AL and ACSR conductors, Color Code: Red (Side A), Red (Sdie B)",
				"item_variant_id": "224647",
				"price": "3.29"
			},
			{
				"currency": "CAD",
				"index": 9,
				"item_group_id": "297492",
				"item_id": "297492",
				"item_name": "BRACKET",
				"item_variant_id": "297492",
				"price": "726.71"
			},
			{
				"currency": "CAD",
				"index": 10,
				"item_category": "Locking",
				"item_group_id": "99208",
				"item_id": "99208",
				"item_name": "Turnlok Isolated Ground Receptacles",
				"item_variant_id": "99208",
				"price": "39.72"
			},
			{
				"currency": "CAD",
				"index": 11,
				"item_group_id": "321014",
				"item_id": "321014",
				"item_name": "AccuSine PCS+ 200A 208-240 VAC IP00",
				"item_variant_id": "321014",
				"price": "37065.38"
			},
			{
				"currency": "CAD",
				"index": 12,
				"item_group_id": "311457",
				"item_id": "311457",
				"item_name": "Cement Library for PES - Medium",
				"item_variant_id": "311457",
				"price": "7354.34"
			},
			{
				"currency": "CAD",
				"index": 13,
				"item_category": "Wire & Cable Labels",
				"item_group_id": "177447",
				"item_id": "177447",
				"item_name": "Self-laminating Vinyl Labels, 1.750 in H x 0.75 in W Clear/White Roll of 10000",
				"item_variant_id": "177447",
				"price": "1003.74"
			},
			{
				"currency": "CAD",
				"index": 14,
				"item_category": "Enclosure Panels",
				"item_group_id": "17264",
				"item_id": "17264",
				"item_name": "Concept Panels, 46.20x46.20, White, Steel",
				"item_variant_id": "17264",
				"price": "413.55"
			},
			{
				"currency": "CAD",
				"index": 15,
				"item_category": "Wire Marker Books",
				"item_group_id": "233379",
				"item_id": "233379",
				"item_name": "Porta-Pack® Wire Marker Book - Repositionable Vinyl Cloth, Legend 46 to 90",
				"item_variant_id": "233379",
				"price": "17.39"
			},
			{
				"currency": "CAD",
				"index": 16,
				"item_group_id": "775421",
				"item_id": "775421",
				"item_name": "RED DELICIOUS RENU USB CHARGER 15A RECEPTACLE FACE PLATE",
				"item_variant_id": "775421",
				"price": "7.43"
			},
			{
				"currency": "CAD",
				"index": 17,
				"item_group_id": "419907",
				"item_id": "419907",
				"item_name": "",
				"item_variant_id": "419907",
				"price": "687.65"
			},
			{
				"currency": "CAD",
				"index": 18,
				"item_category": "Wireway Fittings & Accessories",
				"item_group_id": "362032",
				"item_id": "362032",
				"item_name": "AL FIT 7IN 6W VEN HOR. BEND 60D24R",
				"item_variant_id": "362032",
				"price": "350.95"
			},
			{
				"currency": "CAD",
				"index": 19,
				"item_category": "Replacement Blades",
				"item_group_id": "34052",
				"item_id": "34052",
				"item_name": "DIE UNIT-KEY 1.265 DIA X .156 KEY",
				"item_variant_id": "34052",
				"price": "349.71"
			},
			{
				"currency": "CAD",
				"index": 20,
				"item_category": "Accessories",
				"item_group_id": "159996",
				"item_id": "159996",
				"item_name": "CONTROL STATION 600VAC 5A T-B FORWARD REVERSE",
				"item_variant_id": "159996",
				"price": "110.42"
			}
		]
	}
]

POST | https://stats.ksearchnet.com/analytics/collect

**Comment by jayaraj-dckap** [comment]
How can we remove the specific product from the trending list? from the Klevu admin panel.

Because this error due name is not available for the one product that's been getting this error, can we able to change the name non-mandatory field in this API?

**Comment by rallu** [comment]
Now I think I understand. So the problem is that `sendRecommendationViewEvent()` crashes when product is missing a field like name. I think this is a bug. 

You can remove specific product from results with [exclude() modifier](https://headless.developers.klevu.com/klevucore-reference/exclude). Just add it after `sendRecommendationViewEvent()` in your request.
