### ISSUE TITLE
Explanation Requried for sendRecommendationViewEvent

### ISSUE THREAD

**Issue by jayaraj-dckap** [klevultd/frontend-sdk#105]
sendRecommendationViewEvent()

What is the purpose of this function can give elaborate details about this function?

**Comment by jerrypena1** [comment]
Hi @jayaraj-dckap This function is designed to automatically send an event back to Klevu to update our analytics. As the name implies, this is the event fired when a particular recommendation is viewed. 

We will add this information to our online documentation.
