### ISSUE TITLE
Helper Function to clear all active filters

### ISSUE THREAD

**Issue by rutledgespence** [klevultd/frontend-sdk#117]
Is there a way to create a quick helper function to clear all active filters in one click. 

I see this is a standard feature on the Klevu Shopify templates.

**Comment by rallu** [comment]
Yes there is. Check end of this documentation https://docs.klevu.com/headless-sdk/filter-manager

**Comment by rutledgespence** [comment]
Hey @rallu thanks for the reply. Would it be possible to see a working example of this in one of the examples in the repo. When I go to use it I keep getting 
TS2339: Property 'clearOptionSelections' does not exist on type 'FilterManager'. 

So would be super beneficially to have a representation of the implementation.

**Comment by rallu** [comment]
Do you have the latest version of the library? This feature was added to `FilterManager` in 1.1.6.

**Comment by rutledgespence** [comment]
Yes I'm on    
"@klevu/core": "^1.1.6",

**Comment by rallu** [comment]
Finally found the bug. Filter manager wasn't telling UI that filters have changed. This made using the clearing a bit harder. Fix coming up soon.

**Comment by rutledgespence** [comment]
Thanks @rallu appreciate you digging into this!

**Comment by rallu** [comment]
This was released couple version ago.
