### ISSUE TITLE
listFilters not reacting to "exclude".

### ISSUE THREAD

**Issue by MaiLyLeBrandung** [klevultd/frontend-sdk#127]
Dear Klevu Team, 

We are fetching trending products and implementing the quick search with listFilters. But no matter whether we state an array of fields for the "include" prop or the "exclude" or even stating fields for both, we are getting all fields of each product. Can you please look into that? That would be amazing. Thank you!

**Comment by rallu** [comment]
Could you provide an example of the request you are making? The contents of `KlevuFetch` would be nice to see.

**Comment by jerrypena1** [comment]
Hi @MaiLyLeBrandung, I just wanted to follow up on the previous question. Could you please provide an example of the request you are making?
