### ISSUE TITLE
Configuration missing when trying use Quick Search in hydrogen

### ISSUE THREAD

**Issue by mdunbavan** [klevultd/frontend-sdk#134]
Hi,

I have come across an issue where Klevu looks for configuration in an async function. Below is what is sent back:

```
config.js:19 Uncaught (in promise) Error: Configuration missing
    at KlevuConfig.getDefault (config.js:19:19)
    at klevuFetch.js:35:215
    at Generator.next (<anonymous>)
    at fulfilled (klevuFetch.js:4:58)
```

I have used the Hydrogen example and setup the search that way accordingly eg below in an init.js file.

```
import {KlevuConfig} from '@klevu/core';
import Axios from 'axios';

export const credentials = {
  url: 'https://eucs30v2.ksearchnet.com/cs/v2/search',
  apiKey: '**************'
};

KlevuConfig.init({
  ...credentials,
  axios: Axios,
});
```

Then inside the App.server.jsx file I have included the above with the KlevuInit function wrapped over the app itself, see below:

```
export function KlevuInit(props) {
  KlevuConfig.init({
    ...credentials,
    axios: Axios,
  });

  return props.children;
}
```

All is setup as it should be.

Can anyone help?

**Comment by rallu** [comment]
I found in my Hydrogen tests, that you need to include configuration also into index.html file. 

Like this: https://github.com/klevultd/frontend-sdk/blob/master/examples/hydrogen/index.html#L11 

Otherwise config is not found in the frontend.

**Comment by mdunbavan** [comment]
@rallu this worked like a charm, thanks a lot
