### ISSUE TITLE
Questions related to Javascript SDK

### ISSUE THREAD

**Issue by jainammagneto** [klevultd/frontend-sdk#135]
1) How to fetch the categories list?
2) How can we identify whether the data is configurable or simple in product list data?
3) How to paginate in react SDK?
4) How to fetch configurable products at the minimum price?
5) Product Url is not valid

**Comment by rallu** [comment]
Hello! Here are answers:

1. We do not provide API to list categories. You need to use your source system API's for that. 
2. It depends on your case. Please contact Klevu support here https://help.klevu.com/support/tickets/new?cmd=sdk to get your answer.
3. You can provide `offset` and `limit` parameters to your `search()` or `categoryMerchandising()` queries parameter. You keep track of them with your own logic. For example if user presses page four then set offset to limit * 3 and limit to limit.
4. You pass a filter with `klevu_price` to query. Using `applyFilters` modifier
5. Product URL is what your source system has sent to Klevu. Once again this depends on your source system. Our support helps here https://help.klevu.com/support/tickets/new?cmd=sdk

**Comment by jainammagneto** [comment]
Thanks for the update


*Thanks & Regards,*

*Jainam Paresh MehtaTeam Lead - Magneto IT Solutions*
