### ISSUE TITLE
Morland - Delivery pages 

### ISSUE THREAD

**Issue by avillanyi** [klevultd/frontend-sdk#195]
If you look at the underlining API call for that search page you can see that we are indexing that CMS content and returning it in the response.
So the issue here is that the front-end isn't rendering the CMS data being returned in the API response.
![screenshot - delivery cms search](https://user-images.githubusercontent.com/122283417/211320146-507d3b19-f1d0-4e8e-be95-ad8b32acc658.JPG)

When you search on "delivery" in the search field for instance, you should be also able to see search results found on eg. FAQ page. We have added meta descriptions to the FAQ page eg. delivery but still it isn`t showing up on front end. 

Can you please advise? 
Thanks, 
Anett

**Comment by SpMhmdTako** [comment]
Hi @rallu,

We already have cms included in search overlay as pages. The way we are fetching cms is through `searchCms()` function that is used in `klevuFetch`. We want to fetch magento cms pages that have meta keywords that match search term.

**Comment by rallu** [comment]
Sounds like a indexing issue. I recommend contacting our support to go through the problem.

Here is link to submit a ticket:
https://help.klevu.com/support/tickets/new

**Comment by SpMhmdTako** [comment]
Will do that. Thank you!
