### ISSUE TITLE
Morland UK: URL Redirects not working

### ISSUE THREAD

**Issue by avillanyi** [klevultd/frontend-sdk#197]
URL Redirects not working, how can we resolve this? 
Example: frequently asked questions - no results on front end. FAQ page has been setup under url redirects.

Thanks, 
Anett

**Comment by rallu** [comment]
You need implement redirects yourself. SDK doesn't do it for you as the router of the system is in your hands. 

You can fetch the set redirects with following code:

```
const settings = await KlevuKMCSettings()
const redirects = settings.maps.klevu_keywordUrlMap
```

And then in your code before making the search queries you need to iterate redirects and if search term is what is found then do the redirect with your router.
