### ISSUE TITLE
Customers Also Bought

### ISSUE THREAD

**Issue by rutledgespence** [klevultd/frontend-sdk#206]
Hoping we can get some clarity on the Cart/Checkout Recommendation widget. We are trying to get recommendations from Klevu similarly to how the react app is setup. However in both our react code setup as well as the react example here. Neither are pulling records into the query. Can you take a look and let us know what we are missing. I've included the cart productIds on our end cartProductIds: [...] and while the query renders no items are returned.

```
 const result = await KlevuFetch(
      kmcRecommendation(
        config.checkoutPageRecommendationId,
        {
          id: "alsobought",
          cartProductIds: cart.items.map((p) => p.id),
        },
        sendRecommendationViewEvent("Also bought together KMC recommendation")
      )
    )
```

**Comment by jerrypena1** [comment]
Hi @rutledgespence 

This code looks correct to me. Besides the product IDs needing to be sent as strings (see below), I do know that you will only get recommendations when the products sent in the cartProductIds array have been purchased with another product at least three times. In other words, if you are passing in products that have not been purchased before or have only been purchased 1 or 2 times with another specific product, then Klevu wont be able to send a recommendation. 

Regarding the IDs, I would just do something like this instead:

`cartProductIds: cart.items.map((p) => ""+p.id)`

**Comment by rutledgespence** [comment]
Makes sense! Was returning 0 results for some of the ids we had but assuming we can build a fallback to that. Seems to be working with some of our higher purchased skus.
