### ISSUE TITLE
customANDQuery is misspelled in the query settings

### ISSUE THREAD

**Issue by jerrypena1** [klevultd/frontend-sdk#212]
Instead of customANDQuery, the settings are looking for costum**e**ANDQuery which does not exist. 

Doing a search of the repo, you can find all the instances where the setting is incorrect. 
https://github.com/klevultd/frontend-sdk/search?q=customeANDQuery

I've submitted a [pull request](https://github.com/klevultd/frontend-sdk/pull/211) with the fix.

**Comment by rallu** [comment]
Merged
