### ISSUE TITLE
kmcRecommendation doesn't support BOUGHT_TOGETHER_PDP logic

### ISSUE THREAD

**Issue by kzulis** [klevultd/frontend-sdk#236]
It looks like Product page "Also Bought Together" block is using logic that's not supported by `kmcRecommendation`:
```
export enum KMCRecommendationLogic {
  Trending = "TRENDING",
  TrendingPersonalized = "TRENDING_PERSONALIZED",
  NewestArrivals = "NEWEST_ARRIVALS",
  RecentlyViewed = "RECENTLY_VIEWED",
  HandPicked = "HAND_PICKED",
  OtherAlsoViewed = "OTHER_ALSO_VIEWED",
  Similar = "SIMILAR",
  BoughtTogether = "BOUGHT_TOGETHER",
}
```

Response from `https://config-cdn.ksearchnet.com/recommendations/klevu-API_KEY/settings/REC_ID`
```
{
   "metadata":{
      "title":"Product page",
      "recsKey":"...",
      "pageType":"PRODUCT",
      "logic":"BOUGHT_TOGETHER_PDP",
      "maxProducts":10,
      "productThreshold":1,
      "enabled":true
   },
}
```

Search request for this block is performed without current product ID.

**Comment by jerrypena1** [comment]
Hi @kzulis, As long as you are passing in the proper ids you should be good. Look at the example found in the react product page: https://github.com/klevultd/frontend-sdk/blob/master/examples/react/src/routes/ProductPage.tsx

      kmcRecommendation(
        config.productPageRecommendationId,
        {
          id: "alsoviewed",
          currentProductId: params.id,
          itemGroupId: params.groupId,
        },
        sendRecommendationViewEvent("Also viewed KMC recommendation")
      )

**Comment by jerrypena1** [comment]
oops, nevermind. I just reread your message.

**Comment by jerrypena1** [comment]
@rallu from what I can tell, there seem to be two new KMCRecommendationLogic types; 'BOUGHT_TOGETHER_PDP' and 'VISUALLY_SIMILAR'. I've got quite a bit on my plate, but I'll try to submit a pull request for them. 

Here is the [documentation on the Visually Similar Recommendations](https://docs.klevu.com/apis/smart-recommendations-visually-similar)
