### ISSUE TITLE
Promo banner in Quick Search

### ISSUE THREAD

**Issue by asunny4375** [klevultd/frontend-sdk#255]
In search dropdown (quick search) I could see a banner on top. 
Is this available in Klevu? If yes, how this is added to Klevu? 
Is it possible to retrieve using the Klevu SDK (react)? 
Please let us know how to retrieve this image data.

![c90d15d9-acae-41ba-93fb-d56795d723d2](https://github.com/klevultd/frontend-sdk/assets/61045391/32b32bbd-1296-48a3-96d1-c5bcda4ac2b5)

**Comment by rallu** [comment]
Hello. These banners can be fetched using `KlevuKMCSettings()` function. It can be imported from `@klevu/core`. 

Or you can write your own fetch that fetches the data. More information can be found from here: https://docs.klevu.com/apis/banners
