### ISSUE TITLE
SDK support for Klevu search dropdown

### ISSUE THREAD

**Issue by asunny4375** [klevultd/frontend-sdk#261]
Hi,

I am trying to integrate Klevu search dropdown in Magento headless project which is in progress. In the current live site I could see when no result page is coming there "popular search" and "you may like" section. Can you let us know how this Klevu features are bing retrieved using the Klevu SDK (react)

1. Popular searches
2. "You May Like" product section (Customisations ->  No Results Found Personalization -> Personalized Error Recommendations -> Show popular products)
3. Recent Searches
4. "Recently viewed" products
5. In search dropdown (quick search) I could see a banner on top. Could see different banner if results are available and if no result. Please let me know how this is being configured in Klevu dashboard and how this Klevu features are bing retrieved using the Klevu SDK

Note : Need to use SDK **react** for Klevu search

**Comment by rallu** [comment]
Here is a new documentation page on getting those settings: https://docs.klevu.com/headless-sdk/klevu-merchant-center-settings

**Comment by rallu** [comment]
Sounds like there is a problem with the backend side of things. Please contact our support and they can debug your account and check the settings: https://help.klevu.com/support/tickets/new

**Comment by rallu** [comment]
Closing as inactive
