### ISSUE TITLE
FilterManager.readFromURLParams should take care of multiple values in the URL

### ISSUE THREAD

**Issue by Youhan** [klevultd/frontend-sdk#266]
if you select multiple values for a filter the URL goes from `o_color=red` to `o_color=red%2Cblue`. Now when reading it back we should not set the value of the filter to `red,blue`, instead we need to add multiple options, I guess.

so, on file `packages/klevu-core/src/store/filterManager.ts` Line 363 we could use

```
const values = value.split(",")
for (const optionValue of values) {
    this.selectOption(optionKey, optionValue)
}
```

instead of 
```
this.selectOption(optionKey, value)
```

**Comment by rallu** [comment]
Good catch! That is a logical bug. I need to add tests for multiple selected values.

**Comment by rallu** [comment]
Released
