### ISSUE TITLE
'itemGroupdId' is required for Product recommendation

### ISSUE THREAD

**Issue by kzulis** [klevultd/frontend-sdk#270]
Is `itemGroupdId` really required for PDP recommendations?

<img width="744" alt="Screen Shot 2023-05-31 at 12 13 26" src="https://github.com/klevultd/frontend-sdk/assets/253333/0e68462f-86dd-496d-bbe5-75757e905a61">

Products in our catalog don't have `itemGroupdId` value, so what value should we use when fetching recommendations?

**Comment by rallu** [comment]
Ah. That is a logic bug. Fixing ASAP.

**Comment by rallu** [comment]
Released in 2.0.6
