### ISSUE TITLE
"currentProductId" should be in "recentObjects" instead of "sourceObjects" for PDP recommendations 

### ISSUE THREAD

**Issue by kzulis** [klevultd/frontend-sdk#275]
I'm not sure about `VisuallySimilar` and `Custom` but for `BoughtTogetherPDP` product ID in the request should be under `recentObjects` instead of `sourceObjects`.

<img width="1137" alt="Screen Shot 2023-06-02 at 18 55 52" src="https://github.com/klevultd/frontend-sdk/assets/253333/ae3b63af-8d90-499d-9c57-ef9ffd6cc895">

<img width="1135" alt="Screen Shot 2023-06-02 at 18 57 19" src="https://github.com/klevultd/frontend-sdk/assets/253333/22658d49-f451-4a53-871e-8ff722c44d36">

**Comment by jerrypena1** [comment]
@kzulis I've submitted a pull request with a fix
