### ISSUE TITLE
ExcludeIds Limitation

### ISSUE THREAD

**Issue by mattgrul** [klevultd/frontend-sdk#316]
Hello,

I am using the Headless SDK to build up a custom search, this all works great and has no issues apart from when I try to use the excludeIds param.

Specifically this issue has been noticed when using excludeIds in the searchCms call. I have noticed this maybe what seems to be a length issue of the number of items added to the excludeIds. For example if I pass the string of ID's below then the search result still works.

275,295,303,318,325,319,336,337,338,346,347,348,349,350,354,358,360,366,367,368,372,388,389,400,405,406,415,416,444,445,446,447,449,450,451,452,453,454,471,480,486,491,492,500,512,524,538,543,579,578,584,593,594,597,598,599,616,617,618,619,620,621,622,623,624,625,627,628,629,630,631,632,634,635,643,646,651,652,663,665,671,672,673,674,676,677,678,679,680,681,682,683,685,686,687,688,689,690,691,692,693,694,695,697,698,700,701,702,703,704,705,706,707,708,709,710,711,712,713,714,715,716,717,718,719,721,722,723,724,725,726,727,728,729,730,731,732,733,734,735,736,737,738,740,739,741,742,743,744,746,747,748,749,751,752,753,754,755,756,757,758,759,760,761,762,763,764,765,766,767.768,769,770,771,772,773,775,776,777,778,779,780,781,782,783,784,785,786,787,788,789,790,791,792,793,794,795,796,797,798,799

However as soon as I try to add 1 more item to this list we then get an error back from the search and it no longer works. Is there some limit on the amount of Ids that can be added to the excludeIds option, and if so how can I overcome this problem?

Thanks.
Matt.

**Comment by mattgrul** [comment]
@rallu Thank you, I thought this initially and support directed me over to here to raise the issue. I have gone back to them with the update.

Thank You.

**Comment by rallu** [comment]
Closing as inactive and issue is related to API than the SDK.
