### ISSUE TITLE
 fetch products by category (by category name)  to show the products on category page 

### ISSUE THREAD

**Issue by hmvmpire** [klevultd/frontend-sdk#363]
https://github.com/klevultd/frontend-sdk/blob/master/examples/react/src/routes/CategoryPage.tsx
i refer this and try this code but its not showing the results and in network I checked its 200 response but not result

**Comment by hmvmpire** [comment]
my catalog is import from magento 2 & its working fine on magento 2 but its not showing result with sdk

**Comment by rallu** [comment]
I think it's best for you to contact our support guys so they can debug your environment better. Create ticket here: https://help.klevu.com/support/tickets/new

**Comment by hmvmpire** [comment]
already contacted they told to open issue here

**Comment by rallu** [comment]
Ah! Sorry! Now I understand. I checked it out and looks like the demo store we are using for that example has source data changed.

**Comment by rallu** [comment]
Here is the file running in the server and it's working fine: https://headlessdemo.klevu.com/category/women

Are you trying to run it locally?

React example has changed a little bit. You need to build `core` package before you can run it.

So for example: 
```
cd packages/klevu-core/
npm install
npm run build
cd ../../examples/react
npm install
npm start
```
