### ISSUE TITLE
Question: How to get recommendations title

### ISSUE THREAD

**Issue by ogflow** [klevultd/frontend-sdk#368]
I wonder how can I get a recommendations title that is returned in metaData object? So far I haven't found any methods suitable for that. Neither that data is available in the result returned by await KlevuFetch(kmcRecommendation(recommendationID)).

**Comment by rallu** [comment]
Now that I'm thinking about it and reading the source. There isn't any way. We have set that metadata in private variable inside a class. 

Luckily the change is quite simple. Though it isn't the prettiest solution. Going to release this soonish.

**Comment by ogflow** [comment]
> My previous comment is wrong. There is way to get the recommendation title from the results like this:
> 
> ```ts
> const res = await KlevuFetch(kmcRecommendation(recommendationID))
> const query = res.queryById("kmcrecommendation")
> const metadata = query.func.params?.kmcConfig?.metadata
> 
> console.log(metadata.spotName)
> ```

Great, thank you so much!

would be better however to add a simple method to get it, rather than using this hacky workaround :)

**Comment by rallu** [comment]
Does this look cleaner? https://github.com/klevultd/frontend-sdk/pull/371
