### ISSUE TITLE
how to fetch products by brand

### ISSUE THREAD

**Issue by hmvmpire** [klevultd/frontend-sdk#465]
can you please specify how to fetch products by brands in headless sdk

**Comment by rallu** [comment]
For that you need to make custom query. 

API documentation here: https://docs.klevu.com/apis/smart-search-examples#8x7Uc

In SDK you can any API request with `raw()` function.

So the example in link above would be in SDK code:

```ts
await KlevuFetch(
  raw({
    id: "search",
    settings: {
       customANDQuery: "(size:\"Small\" OR size:\"Medium\") AND -(brand:\"KKE\")",
       fields: ["id","name","size","brand"],
       limit: 10
    }
  })
)
```

**Comment by rallu** [comment]
I was informed that `customANDQuery` is being deprecated and we should use our new updated advanced filtering.

For that we have handy modifier for you to use:

```ts
await KlevuFetch(
  search(
    "*", 
    { limit: 10 }, 
    advancedFiltering([
      {
        key: "brand",
        valueOperator: "INCLUDE",
        singleSelect: false,
        values: ["MNH"]
      }
    ])
  ) 
)
```
