### ISSUE TITLE
How do I send a simple search to analytics

### ISSUE THREAD

**Issue by danielschneider22** [klevultd/frontend-sdk#629]
I've forked a sandbox of setting up a simple search here https://codesandbox.io/p/sandbox/klevu-headless-sdk-hello-world-forked-k4py5z?file=%2Fsrc%2Findex.ts%3A4%2C1-5%2C1.

I want to be able to track when a user searches using a custom search using klevu analytics.

Basically when I call:

`const result = await KlevuFetch(search("dress"));`

I want this search to reflect here: https://box.klevu.com/analytics/km?cmd=realtimeAnalyticsPg.

I was told this was part of https://docs.klevu.com/headless-sdk/result-object, but that doesn't seem to match my exact usecase from what I can tell

**Comment by jerrypena1** [comment]
Hi @danielschneider22 

What you would use is actually the **sendSearchEvent()** modifier within the **search()** call. 

The **search()** call takes the _search term_ and _request settings_ as the first two function parameters, followed by any number of modifiers. 

Here's an example: 

`const result = await KlevuFetch( search( "dress", {}, sendSearchEvent() ) );`

Here's another example from the React code in the repo for the search page: https://github.com/klevultd/frontend-sdk/blob/master/examples/react/src/routes/SearchResultPage.tsx

I hope this is helpful. Let us know if you still have any issues.

Juan

**Comment by danielschneider22** [comment]
That worked perfectly! Thank you so much!
