### ISSUE TITLE
How to re-initialize template based on new search

### ISSUE THREAD

**Issue by danielschneider22** [klevultd/frontend-sdk#631]
I have a klevu search input that I want to live update the contents of my template landing page.

After initialization, I want the contents of the landing page to dynamically update based on either the new url (which I'm changing on the input change) or I can kick off the new process manually. I don't want to submit the form refreshing the page.

I've tried the following but neither changes the layout:
1. Re-run klevu(options); after changing the query params
2. Run klevu.reInitialize()

I've set-up a sandbox here: https://codesandbox.io/p/sandbox/klevu-headless-sdk-hello-world-forked-k9yryy?file=%2Fsrc%2Finit.ts%3A29%2C36

**Comment by jerrypena1** [comment]
Hi @danielschneider22 I'm trying to see what that code would look like. Give me a little while 

Juan

**Comment by jerrypena1** [comment]
You may try something like this: 

```
var term = "polish"
function updateSearchResults(term){
    var scope = klevu.search.landing.getScope().element;
    // change search term for productList query
    klevu.setObjectPath(
      scope.kScope.data,
      "localOverrides.query.productList" + ".settings.query.term",
      term
    );
    
    scope.kScope.data = scope.kObject.resetData(scope.kElem);
    // fire search event
    klevu.event.fireChain(
      scope.kScope,
      "chains.events.keyUp",
      scope,
      scope.kScope.data,
      window.event
    );    
}
updateSearchResults(term)
```

Juan

**Comment by danielschneider22** [comment]
Amazing! That worked perfectly. Thanks so much!
