### ISSUE TITLE
Version 1.1.4 throws error import error

### ISSUE THREAD

**Issue by MaiLyLeBrandung** [klevultd/frontend-sdk#99]
Dear Klevu Team, 

We are using klevu/core version 1.1.4 for our React Next.js project. However, we are getting the error: 

`Error: Directory import '[project]/node_modules/@klevu/core/dist/mjs/utils' is not supported resolving ES modules imported from [project]/node_modules/@klevu/core/dist/mjs/config.js`

Right now, we replaced the first line of the file "node_modules/@klevu/core/dist/mjs/config.js"  with 

`export const isBrowser = () => ![typeof window, typeof document].includes("undefined");`

instead of importing the function to make it work. 

Hope that you have time to check on this soon and thanks for the work!

**Comment by rallu** [comment]
Ah! Nice find. Looks like there is missing `.js` suffix in util import in https://github.com/klevultd/frontend-sdk/blob/master/packages/klevu-core/src/config.ts

**Comment by rallu** [comment]
`@klevu/core` version 1.1.5 has been released. It fixes this problem.
